on:
  push:
    branches:
      - tvmbeta
name: Publish to NPM
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          always-auth: true
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
      - name: Build
        run: yarn build
      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmAuthToken $NPM_AUTH_TOKEN
          yarn config set npmAlwaysAuth true
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: yarn npm publish --access public --tag tvmbeta
