name: QA

on:
  push:
    paths-ignore:
      - '.github/workflows/publish.yml'
      - '.github/workflows/publish-dev.yml'
      - '.github/workflows/reward.yml'
      - '.github/workflows/reward-merged-prs.yml'
      - '.github/ISSUE_TEMPLATE/*'
      - 'examples/*'
      - '*.md'
      - '*.png'
    branches:
      - main
      - develop
  pull_request:
    paths-ignore:
      - '.github/workflows/publish.yml'
      - '.github/workflows/publish-dev.yml'
      - '.github/workflows/reward.yml'
      - '.github/workflows/reward-merged-prs.yml'
      - '.github/ISSUE_TEMPLATE/*'
      - 'examples/*'
      - '*.md'
      - '*.png'
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: the-ton-tech/toolchain/lint@v1.4.0
        with:
          node-version: '18.x'
  build:
    name: Test & Build (Node ${{ matrix.node-version }})
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '18.x'
          - '22.x'
    steps:
      - uses: the-ton-tech/toolchain/build@v1.4.0
        with:
          node-version: ${{ matrix.node-version }}
