name: Test Example

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  test-example:
    name: Test Example
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Fetch Sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.3.14'

      - name: Patch example and test execution
        run: |
          bun install --frozen-lockfile
          bun run build
          cd examples
          bun install --frozen-lockfile
          bun run examples
